<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-browser</TargetFramework>
        <Platforms>AnyCPU;x64</Platforms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <!-- <StartupObject>Avalonia.DesignerSupport.Remote.RemoteDesignerEntryPoint</StartupObject>-->
    </PropertyGroup>
    <PropertyGroup Label="Avalonia">
        <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="Roots.xml" />
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\VariableBox.Demo\VariableBox.Demo.csproj" />
    </ItemGroup>
</Project>
