using System;
using VariableBox.Common;

namespace VariableBox;

// This file is now empty because all concrete classes are generated by VariableBox.Generators.
// See AssemblyInfo.cs for the list of generated types.
