<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-android</TargetFramework>
        <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <ApplicationId>com.irihitech.Ursa</ApplicationId>
        <ApplicationVersion>1</ApplicationVersion>
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <AndroidPackageFormat>apk</AndroidPackageFormat>
        <AndroidEnableProfiledAot>False</AndroidEnableProfiledAot>
        <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
        <RootNamespace>Ursa.Demo.Android</RootNamespace>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>
    <PropertyGroup Label="Avalonia">
      <AvaloniaUseCompiledBindingsByDefault>True</AvaloniaUseCompiledBindingsByDefault>
      <ApplicationIcon>logo.ico</ApplicationIcon>
      <PackageIcon>Logo.png</PackageIcon>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
      <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
      <IsAotCompatible>True</IsAotCompatible>
    </PropertyGroup>

    <ItemGroup>
        <AndroidResource Include="Icon.png">
            <Link>Resources\drawable\Icon.png</Link>
        </AndroidResource>
    </ItemGroup>

    <ItemGroup>
      <Content Include="logo.ico" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\Logo.png">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Android" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" Version="1.0.1.14" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Ursa.Demo\Ursa.Demo.csproj" />
    </ItemGroup>
</Project>
