<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../Package.props" />

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8;net9;</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <Version>$(VariableBoxVersion)</Version>
        <Authors>heartacker</Authors>
        <PackageId>VariableBox.Avalonia</PackageId>
        <PackageIcon></PackageIcon>
        <PackageProjectUrl>https://github.com/heartacker/VariableBox.Avalonia</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
        <Description>Numeric Updown GetSetBox
            Items Updown GetSetBox
            Enums Updown GetSetBox</Description>
        <Copyright>MIT</Copyright>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Controls\Panels\" />
        <None Include="..\..\README.md">
          <Pack>True</Pack>
          <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>
</Project>
