<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>Preview</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="Roots.xml" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
        <!--Condition
        below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics"
            Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Semi.Avalonia" Version="$(SemiAvaloniaVersion)" />
        <PackageReference Include="Irihi.Ursa" Version="1.10.0" />
        <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="1.10.0" />
        <!-- <PackageReference Include="AtomUI" Version="0.0.1-build-20241009" />-->
        <!-- <PackageReference Include="HotAvalonia" PrivateAssets="All" Publish="True" Version="3.0.0" /> -->
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\VariableBox\VariableBox.csproj" />
    </ItemGroup>
</Project>