<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0-ios</TargetFramework>
        <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>
        <Nullable>enable</Nullable>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.iOS" Version="$(AvaloniaVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\VariableBox.Demo\VariableBox.Demo.csproj" />
    </ItemGroup>

</Project>
