<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <AvaloniaVersion>11.3.2</AvaloniaVersion>
    <SemiAvaloniaVersion>11.2.1.9</SemiAvaloniaVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HotAvalonia" PrivateAssets="All" Publish="True" Version="3.0.0" />
  </ItemGroup>
</Project>
