<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>Preview</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootDescriptor Include="Roots.xml" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />
        <!--Condition
        below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
        <PackageReference Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
        <PackageReference Include="Semi.Avalonia" Version="$(SemiAvaloniaVersion)" />
    </ItemGroup>
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DefineConstants>$(DefineConstants);ENABLE_XAML_HOT_RELOAD1</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Condition="$(DefineConstants.Contains(ENABLE_XAML_HOT_RELOAD))" Include="Avalonia.Markup.Xaml.Loader" Version="$(AvaloniaVersion)" />
        <PackageReference Condition="$(DefineConstants.Contains(ENABLE_XAML_HOT_RELOAD))" Include="HotAvalonia" Version="2.1.0" />
        <PackageReference Include="HotAvalonia.Extensions" Version="2.1.0" PrivateAssets="All" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Models\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\VariableBox.Themes.Semi\VariableBox.Themes.Semi.csproj" />
        <ProjectReference Include="..\..\src\VariableBox.Themes\VariableBox.Themes.csproj" />
    </ItemGroup>
</Project>